## 기능개발 (스택/큐)
기능은 진도가 100%일 때 서비스에 반영 가능  
뒤에 있는 기능이 앞에 있는 기능보다 먼저 개발될 수 있다.  
뒤에 있는 기능은 앞에 있는 기능이 배포될 때 함께 배포된다.  

progresses : 배포되어야하는 순서대로 작업의 진도가 적힌 배열  
speeds : 각 작업의 개발 속도 배열  

리턴 : 배포마다 몇 개의 기능이 배포되는지  

제한사항  
- progresses 길이 : 100 이하
- 작업 진도 : 100 미만 자연수
- 작업 속도 : 100 이하 자연수
- 배포는 하루에 한 번, 하루 끝 (ex. 진도율이 95인 작업의 속도가 4라면 2일 뒤에 배포)

In [13]:
import math
def solution(progresses, speeds):
    answer = []
    q = []
    for p, s in zip(progresses, speeds):
        q.append(math.ceil((100 - p) / s))
        
    while q:
        cnt = 1
        removed = q.pop(0)
        if not q:
            answer.append(cnt)
            break
        cmp = q.pop(0)
        while removed >= cmp:
            cnt += 1
            if not q:
                cmp = -1
                break
            cmp = q.pop(0)
        if cmp != -1:
            q.insert(0, cmp)
        answer.append(cnt)
    return answer

progresses = [93,30,55]
speeds = [1,30,5]
print(solution(progresses, speeds))

progresses = [50,50,50]
speeds = [1,30,50]
print(solution(progresses, speeds))

progresses = [50,50,50]
speeds = [30,20,10]
print(solution(progresses, speeds))

progresses = [50,50,50]
speeds = [10,10,10]
print(solution(progresses, speeds))

[2, 1]
[3]
[1, 1, 1]
[3]


In [14]:
# 다른 사람
def solution(progresses, speeds):
    Q = []
    for p, s in zip(progresses, speeds):
        if len(Q) == 0 or Q[-1][0] < -((p-100)//s):
            Q.append([-((p-100)//s), 1])
        else:
            Q[-1][1] += 1
        print("p: {}, s: {}".format(p, s))
        print(Q)
    return [q[1] for q in Q]

progresses = [93,30,55]
speeds = [1,30,5]
print(solution(progresses, speeds))

progresses = [50,50,50]
speeds = [1,30,50]
print(solution(progresses, speeds))

progresses = [50,50,50]
speeds = [30,20,10]
print(solution(progresses, speeds))

progresses = [50,50,50]
speeds = [10,10,10]
print(solution(progresses, speeds))

p: 93, s: 1
[[7, 1]]
p: 30, s: 30
[[7, 2]]
p: 55, s: 5
[[7, 2], [9, 1]]
[2, 1]
p: 50, s: 1
[[50, 1]]
p: 50, s: 30
[[50, 2]]
p: 50, s: 50
[[50, 3]]
[3]
p: 50, s: 30
[[2, 1]]
p: 50, s: 20
[[2, 1], [3, 1]]
p: 50, s: 10
[[2, 1], [3, 1], [5, 1]]
[1, 1, 1]
p: 50, s: 10
[[5, 1]]
p: 50, s: 10
[[5, 2]]
p: 50, s: 10
[[5, 3]]
[3]


## 주식가격 (스택/큐)
prices : 초 단위로 기록된 주식 가격이 담긴 배열  

리턴 : 가격이 떨어지지 않은 기간은 몇 초인지(떨어지기까지의 시간)  

제한사항  
prices 길이 : 2 ~ 100,000  
prices의 가격 : 1 ~ 10,000  

In [24]:
def solution(prices):
    answer = []   
    for i in range(len(prices)):
        for j in range(i+1, len(prices)):
            if prices[j] < prices[i]:
                answer.append(j-i)
                break
            if j == len(prices)-1:
                answer.append(j-i)
        if i == len(prices)-1:
            answer.append(0)
    return answer

prices = [1,2,3,2,3]
print(solution(prices))

prices = [1, 2, 3, 2, 3, 3, 1]
print(solution(prices))

[4, 3, 1, 1, 0]
[6, 5, 1, 3, 2, 1, 0]


In [25]:
# 다른 사람
def solution(prices):
    answer = [0] * len(prices)
    for i in range(len(prices)):
        for j in range(i+1, len(prices)):
            if prices[i] <= prices[j]:
                answer[i] += 1
            else:
                answer[i] += 1
                break
    return answer

prices = [1,2,3,2,3]
print(solution(prices))

prices = [1, 2, 3, 2, 3, 3, 1]
print(solution(prices))

[4, 3, 1, 1, 0]
[6, 5, 1, 3, 2, 1, 0]


## 다리를 지나는 트럭
모든 트럭이 다리를 건너려면 최소 몇 초가 걸리는지  
트럭은 1초에 1만큼 움직임   
다리 길이 : bridge_length, 무게 : weight  
다리는 무게까지 견딤  

bridge_length : 다리 길이  
weight : 다리가 견딜 수 있는 무게  
truck_weights : 트럭별 무게  

리턴 : 모든 트럭이 다리를 건너려면 최소 몇 초  

제한조건  
bridge_length : 1 ~ 10,000  
weight : 1 ~ 10,000  
truck_weights길이 : 1 ~ 10,000  
모든 트럭의 무게 : 1 ~ weight  

In [108]:
%%time
def solution(bridge_length, weight, truck_weights):
    answer = 0
    t = len(truck_weights)
    arr = []
    ing = []
    while True:
        answer += 1
        if len(arr) == t:
            break
            
        i = 0
        while i in range(len(ing)):
            ing[i][1] += 1
            if ing[i][1] == bridge_length + 1:
                arr.append(ing[i])
                ing.remove(ing[i])
            else:
                i += 1

        if truck_weights:
            truck = truck_weights.pop(0)
            ing.append([truck, 1])
            w = sum([x[0] for x in ing])
            if w > weight:
                truck_weights.insert(0, truck)
                ing.pop()
    return answer-1

print(solution(2, 10, [7, 4, 5, 6]), 8)
print(solution(100, 100, [10]), 101)
print(solution(100, 100, [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]), 110)

# bridge_length = 2
# weight = 10
# truck_weights = [7,4,5,6]
# print(solution(bridge_length, weight, truck_weights))

# bridge_length = 2
# weight = 10
# truck_weights = [7,4,5,3]
# print(solution(bridge_length, weight, truck_weights))

# bridge_length = 3
# weight = 3
# truck_weights = [1,1,1]
# print(solution(bridge_length, weight, truck_weights))

# bridge_length = 100
# weight = 100
# truck_weights = [10]
# print(solution(bridge_length, weight, truck_weights))

# bridge_length = 100
# weight = 100
# truck_weights = [10,10,10,10,10,10,10,10,10,10]
# print(solution(bridge_length, weight, truck_weights))

8 8
101 101
110 110
CPU times: user 754 µs, sys: 331 µs, total: 1.08 ms
Wall time: 796 µs


In [109]:
# 다른 사람
%%time
import collections

DUMMY_TRUCK = 0

class Bridge(object):
    def __init__(self, length, weight):
        self._max_length = length
        self._max_weight = weight
        self._queue = collections.deque()
        self._current_weight = 0
    def push(self, truck):
        next_weight = self._current_weight + truck
        if next_weight <= self._max_weight and len(self._queue) < self._max_length:
            self._queue.append(truck)
            self._current_weight = next_weight
            return True
        else:
            # push 실패
            return False
    def pop(self):
        item = self._queue.popleft()
        self._current_weight -= item
        return item
    def __len__(self):
        return len(self._queue)
    def __repr__(self):
        return 'Bridge({}/{} : [{}])'.format(self._current_weight, self._max_weight, list(self._queue))

def solution(bridge_length, weight, truck_weights):
    bridge = Bridge(bridge_length, weight)
    trucks = collections.deque(w for w in truck_weights)

    for _ in range(bridge_length):
        bridge.push(DUMMY_TRUCK)

    count = 0
    while trucks:
        bridge.pop()

        if bridge.push(trucks[0]):
            trucks.popleft()
        else:
            bridge.push(DUMMY_TRUCK)

        count += 1

    while bridge:
        bridge.pop()
        count += 1

    return count


def main():
    print(solution(2, 10, [7, 4, 5, 6]), 8)
    print(solution(100, 100, [10]), 101)
    print(solution(100, 100, [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]), 110)


if __name__ == '__main__':
    main()

8 8
101 101
110 110
CPU times: user 586 µs, sys: 466 µs, total: 1.05 ms
Wall time: 681 µs


## 프린터 (스택/큐)
중요도가 높은 문서를 먼저 인쇄  
1. 인쇄 대기목록의 가장 앞에 있는 문서(J)를 대기목록에서 꺼냄
2. 나머지 대기목록에서 J보다 높은 문서가 한개라도 존재하면 J를 대기목록의 가장 마지막에 넣는다
3. 그렇지 않으면 J를 인쇄

example) [A, B, C, D]가 대기목록에 있고 중요도가 2 1 3 2 라면  
[C D A B] 순으로 인쇄. C는 1번째, A는 3번째로 인쇄된다.  

priorities : 대기목록 문서의 중요도 배열  
location : 인쇄를 요청한 문서가 있는 대기목록의 위치    

return : 내가 인쇄 요청한 문서가 몇 번째로 인쇄되는지  

제한사항  
대기목록의 길이 1 ~ 100  
중요도 : 1 ~ 9 클수록 중요하다  
location : 0 ~ (대기목록 작업 수 - 1) 가장 앞 = 0, 두번째 = 1  

In [5]:
def solution(priorities, location):
    target = priorities[location]
    
    pri = []
    for idx, p in enumerate(priorities):
        pri.append([p, idx])
    
    a = []
    while pri:
        j = pri.pop(0)
        printable = True
        for p in pri:
            if p[0] > j[0]:
                pri.append(j)
                printable = False
                break
        if printable:
            a.append(j)
    
    return a.index([target, location]) + 1

priorities = [2, 1, 3, 2]
location = 2
print(solution(priorities, location))

priorities = [1, 1, 9, 1, 1, 1]
location = 0
print(solution(priorities, location))

priorities = [1,2,3,4]
location = 2
print(solution(priorities, location))

[[2, 0], [1, 1], [3, 2], [2, 3]]
[[3, 2], [2, 3], [2, 0], [1, 1]]
1
[[1, 0], [1, 1], [9, 2], [1, 3], [1, 4], [1, 5]]
[[9, 2], [1, 3], [1, 4], [1, 5], [1, 0], [1, 1]]
5
[[1, 0], [2, 1], [3, 2], [4, 3]]
[[4, 3], [3, 2], [2, 1], [1, 0]]
2


In [6]:
# 다른 사람
# deque 를 사용하면 효율성이 좋아진다고 한다..
from collections import deque
def solution(priorities, location):
    answer = 0
    d = deque([(v, i) for i, v in enumerate(priorities)])
    while len(d):
        item = d.popleft()
        if d and max(d)[0] > item[0]:
            d.append(item)
        else:
            answer += 1
            if item[1] == location:
                break
    return answer

priorities = [1, 1, 9, 1, 1, 1]
location = 0
print(solution(priorities, location))

priorities = [1,2,3,4]
location = 2
print(solution(priorities, location))

5
2


## H-Index (정렬)
h = H-index 값 (생산성, 영향력)  
발표한 논문 n편 중, h번 이상 인용된 논문이 h편 이상 && 나머지 논문이 h번 이하 인용 -> h의 최댓값 = H-index  

citation : 논문의 인용 횟수  
return : h-index  

제한  
citation 길이 : 1 ~ 1,000  
인용횟수 : 0 ~ 10,000  

In [42]:
def solution(citations):
    citations = sorted(citations)[::-1]
    idx = 0
    h = citations[idx]
    arr = []
    while True:
        while idx<len(citations) and citations[idx] >= h:
            arr.append(citations[idx])
            idx += 1
        if len(arr) >= h:
            break
        else:
            h -= 1            
    return h

print(solution([3, 0, 6, 1, 5]))
print(solution([3, 0, 6, 1, 5, 5]))
print(solution([1,1,1,1]))

3
3
1


In [43]:
# 다른 사람
def solution(citations):
    citations = sorted(citations)
    l = len(citations)
    for i in range(l):
        if citations[i] >= l-i:
            return l-i
    return 0

print(solution([3, 0, 6, 1, 5]))
print(solution([3, 0, 6, 1, 5, 5]))
print(solution([1,1,1,1]))

3
3
1


In [44]:
# 다른 사람 2
def solution(citations):
    citations.sort(reverse=True)
    answer = max(map(min, enumerate(citations, start=1)))
    return answer

print(solution([3, 0, 6, 1, 5]))
print(solution([3, 0, 6, 1, 5, 5]))
print(solution([1,1,1,1]))

3
3
1


## 위장 (해시)
매일 다른 옷을 조합  

clothes : 스파이 의상 2차원 배열  
리턴 : 서로 다른 옷의 조합 수  

제한  
[의상 이름, 의상 종류]  
의상의 수 : 1 ~ 30개  
같은 이름의 의상은 존재 X  
모든 원소는 문자열  
알파벳 소문자, _ 로만 이루어짐  
최소 한 개의 의상은 입는다  

In [49]:
def solution(clothes):
    answer = 1
    dictionary = dict()
    for cloth in clothes:
        if not cloth[1] in dictionary:
            dictionary[cloth[1]] = []
        dictionary[cloth[1]].append(cloth[0])
    for key in dictionary.keys():
        answer *= (len(dictionary[key]) + 1)
    return answer - 1

print(solution([["yellow_hat", "headgear"], ["blue_sunglasses", "eyewear"], ["green_turban", "headgear"]]))
print(solution([["crow_mask", "face"], ["blue_sunglasses", "face"], ["smoky_makeup", "face"]]))

{'headgear': ['yellow_hat', 'green_turban'], 'eyewear': ['blue_sunglasses']}
5
{'face': ['crow_mask', 'blue_sunglasses', 'smoky_makeup']}
3


In [50]:
# 다른 사람
import collections
from functools import reduce
def solution(c):
    return reduce(lambda x, y: x*y, \
                 [a+1 for a in collections.Counter([x[1] for x in c]).values()])-1

print(solution([["yellow_hat", "headgear"], ["blue_sunglasses", "eyewear"], ["green_turban", "headgear"]]))
print(solution([["crow_mask", "face"], ["blue_sunglasses", "face"], ["smoky_makeup", "face"]]))

5
3


In [54]:
# 다른 사람 2
from collections import Counter
from functools import reduce
def solution(clothes):
    cnt = Counter([kind for name, kind in clothes])
#     print(type(cnt))
    answer = reduce(lambda x, y: x*(y+1), cnt.values(), 1) - 1
    return answer

print(solution([["yellow_hat", "headgear"], ["blue_sunglasses", "eyewear"], ["green_turban", "headgear"]]))
print(solution([["crow_mask", "face"], ["blue_sunglasses", "face"], ["smoky_makeup", "face"]]))

5
3


## 다음 큰 숫자
자연수 n, n의 다음 큰 숫자의 정의  
- n보다 큰 자연수
- 다음 큰 숫자와 n은 2진수로 변환했을 때 1의 갯수가 같다
- 조건 1, 2를 만족하는 수 중 가장 작은 수

리턴 : n의 다음 큰 숫자  

제한 사항  
n : 1 ~ 1,000,000 (10^6)

In [63]:
def solution(n):
    answer = n+1
#     print(format(n,'b').count('1'))
    # format 안 쓰고 그냥 bin함수로 해도 count 가능하다..
#     cnt = format(n,'b').count('1')
    cnt = bin(n).count('1')
    while bin(answer).count('1') != cnt:
        answer += 1
    return answer

print(solution(78))
print(solution(15))

83
23


## * 124 나라의 숫자
수를 표현하는 규칙  
- 자연수만 존재
- 수를 표현할 때 1, 2, 4만 사용

제한 사항  
n : 500,000,000 이하의 자연수  

In [44]:
# 머리가 안 돌아간다 ㅋㅋㅋ;;;
'''
111, 112, 114, 121, 122, 124, 141, 142, 144
211, 212, 214, 
'''
def solution(n):
    answer = ''
    num = ['4', '1', '2']
    while n > 0:
#             answer += str(num[n % 3])
            answer = num[n % 3] + answer
            if n % 3 == 0:
                n -= 1
            n //= 3
    return answer

print(solution(10))
print(solution(2))
print(solution(3))
print(solution(7))
print(solution(11))

41
2
4
21
42


In [45]:
# 다른 사람
def solution(n):
    answer = ''
    num = ['1', '2', '4']
    while n > 0:
        n -= 1
        answer = num[n % 3] + answer
        n //= 3
    return answer
print(solution(10))
print(solution(2))
print(solution(3))
print(solution(7))
print(solution(11))

41
2
4
21
42


## 타겟 넘버 (DFS/BFS)
n개의 음이 아닌 정수  
numbers : 사용할 수 있는 숫자 배열  
target : 타겟 넘버  
타겟 넘버를 만드는 방법의 수를 리턴  

숫자의 개수 : 2 ~ 20  
각 숫자 : 1 ~ 50 자연수  
타겟 넘버 : 1 ~ 1000 자연수  

In [26]:
import copy
def new_sol(numbers, target, count):
    if len(numbers) == 0 and target == 0:
        count.append(1)
    elif len(numbers) == 0:
        pass
    else:
        n = numbers.pop()
        new_sol(copy.deepcopy(numbers), target + n, count)
        new_sol(copy.deepcopy(numbers), target - n, count)
        
def solution(numbers, target):
    count = []
    new_sol(numbers, target, count)
    return sum(count)

numbers = [1,1,1]
target = 2
print(solution(numbers, target))

numbers = [1,1,1,1,1]
target = 3
print(solution(numbers, target))

0
5


In [27]:
# 다른 사람
def solution(numbers, target):
    if not numbers and target == 0:
        return 1
    elif not numbers:
        return 0
    else:
        return solution(numbers[1:], target-numbers[0]) + solution(numbers[1:], target+numbers[0])
    
numbers = [1,1,1]
target = 2
print(solution(numbers, target))

numbers = [1,1,1,1,1]
target = 3
print(solution(numbers, target))

0
5


## 카펫 (완전탐색)
중앙 : 노란색, 테두리 1줄 : 갈색  

brown : 갈색 격자의 수  
yellow : 노란색 격자의 수  

카펫의 가로 크기, 세로 크기를 배열에 담아 리턴  

brown : 9 ~ 5,000  
yellow : 1 ~ 2,000,000  

카펫의 가로 길이 >= 세로 길이  

In [29]:
def solution(brown, yellow):
    answer = []
    area = brown + yellow 
    for w in range(brown // 2, 0, -1):
        h = (brown - w * 2 + 4) // 2
        if w * h == area:
            answer.append(w)
            answer.append(h)
            break
    return answer

print(solution(10, 2))
print(solution(8, 1))
print(solution(24, 24))

[4, 3]
[3, 3]
[8, 6]


In [30]:
# 다른 사람
def solution(brown, yellow):
    for i in range(1, int(yellow**(1/2))+1):
        if yellow % i == 0:
            if 2*(i + yellow//i) == brown-4:
                return [yellow//i+2, i+2]
            
print(solution(10, 2))
print(solution(8, 1))
print(solution(24, 24))

[4, 3]
[3, 3]
[8, 6]


## 소수찾기 (완전탐색)
numbers : 종이 조각에 적힌 숫자 문자열  
리턴 : 만들 수 있는 소수 개수  

제한사항  
numbers 길이 : 1 <= <= 7  
numbers : 0 ~ 9  

In [14]:
from itertools import permutations
items = ['1', '7', '3', '2']
list(permutations(items))

[('1', '7', '3', '2'),
 ('1', '7', '2', '3'),
 ('1', '3', '7', '2'),
 ('1', '3', '2', '7'),
 ('1', '2', '7', '3'),
 ('1', '2', '3', '7'),
 ('7', '1', '3', '2'),
 ('7', '1', '2', '3'),
 ('7', '3', '1', '2'),
 ('7', '3', '2', '1'),
 ('7', '2', '1', '3'),
 ('7', '2', '3', '1'),
 ('3', '1', '7', '2'),
 ('3', '1', '2', '7'),
 ('3', '7', '1', '2'),
 ('3', '7', '2', '1'),
 ('3', '2', '1', '7'),
 ('3', '2', '7', '1'),
 ('2', '1', '7', '3'),
 ('2', '1', '3', '7'),
 ('2', '7', '1', '3'),
 ('2', '7', '3', '1'),
 ('2', '3', '1', '7'),
 ('2', '3', '7', '1')]

In [19]:
list(permutations(items,2))

[('1', '7'),
 ('1', '3'),
 ('1', '2'),
 ('7', '1'),
 ('7', '3'),
 ('7', '2'),
 ('3', '1'),
 ('3', '7'),
 ('3', '2'),
 ('2', '1'),
 ('2', '7'),
 ('2', '3')]

In [23]:
l = list(permutations(items,2))
print(type(l[0]))
print(''.join(l[0]))

<class 'tuple'>
17


In [18]:
from itertools import combinations
items = ['1', '7', '3', '2']
print(list(combinations(items, 1)))
print(list(combinations(items, 2)))
print(list(combinations(items, 3)))

[('1',), ('7',), ('3',), ('2',)]
[('1', '7'), ('1', '3'), ('1', '2'), ('7', '3'), ('7', '2'), ('3', '2')]
[('1', '7', '3'), ('1', '7', '2'), ('1', '3', '2'), ('7', '3', '2')]


In [28]:
from itertools import permutations

def isPrime(num):
    # 소수인지 아닌지 확인
    if num == 0 or num == 1:
        return False
    if num == 2:
        return True
    for d in range(2, num):
        if num % d == 0:
            # 소수 아님
            return False
    return True

# 최대 경우의 수 : 7^7 = 823643
def solution(numbers):
    answer = 0
    numbers = list(numbers)
    prime = []
    for i in range(1, len(numbers)+1):
        for tup in list(permutations(numbers, i)):
            n = int(''.join(tup))
            if n in prime:
                continue
            else:
                if isPrime(n) == True:
                    prime.append(n)
                    answer += 1
    return answer

print(solution("17"))
print(solution("011"))
print(solution("1234"))

3
2
14


In [29]:
# 다른 사람
# 가능한 모든 숫자를 집합에 저장해두고
# 에라토스테네스 체로 제거해 나가는 방식
# 비교) 나: 가능한 숫자를 하나씩 만들 때마다 소수인지 아닌지 확인함
from itertools import permutations

def solution(n):
    a = set()
    for i in range(len(n)):
        a |= set(map(int, map("".join, permutations(list(n), i + 1))))
    a -= set(range(0, 2))
    for i in range(2, int(max(a) ** 0.5) + 1):
        a -= set(range(i * 2, max(a) + 1, i))
    return len(a)

print(solution("17"))
print(solution("011"))
print(solution("1234"))

3
2
14


## 더 맵게(힙)
모든 음식의 스코빌 지수를 K 이상으로 만들고 싶다.  

스코빌 지수가 가장 낮은 2개의 음식을 섞음  
섞은 음식의 스코빌 지수 = 가장 안 매운 음식의 스코빌 지수 + (두번째 * 2)  

모든 음식의 스코빌 지수가 K 이상이 될 때까지 반복하여 섞자.  
scoville : 음식의 스코빌 지수가 담긴 배열  
K : 스코빌 지수  
섞어야 하는 최소 횟수를 리턴  

제한사항  
scoville 길이 : 2 ~ 10^6  
K : 0 ~ 10^9  
모든 음식의 스코빌 지수를 K 이상으로 만들 수 없으면 -1 리턴  

In [33]:
import heapq as heap
def solution(scoville, K):
    answer = 0
    heap.heapify(scoville)
    while True:
        if scoville:
            first = heap.heappop(scoville)
        else:
            answer = -1
            break
        if first >= K:
            break
#         second = heap.heappop(scoville)
        if scoville:
            second = heap.heappop(scoville)
        else:
            answer = -1
            break
        mixed = first + (second * 2)
        heap.heappush(scoville, mixed)
        answer += 1
    return answer

print(solution([1,2,9,12,10,3], 7))

2


In [ ]:
# 다른사람
# 배울 것 : if 문 깔끔하게 정리하기
import heapq as hq
def solution(scoville, K):
    hq.heapify(scoville)
    answer = 0
    while True:
        first = hq.heappop(scoville)
        if first >= K:
            break
        if len(scoville) == 0:
            return -1
        second = hq.heappop(scoville)
        hq.heappush(scoville, first + second*2)
        answer += 1 
    return answer

## N개의 최소공배수
n개의 수의 최소공배수 := n개의 수들의 배수 중 공통이 되는 가장 작은 숫자  
arr : n개의 숫자를 담은 배열(길이 1~15)  
최소공배수를 반환  

In [4]:
import math
def solution(arr):
    lcm = arr[0]
    for i in range(1, len(arr)):
        gcd = math.gcd(lcm, arr[i])
        lcm = arr[i] * lcm // gcd
    return lcm

print(solution([2,6,8,14]))
print(solution([1,2,3]))

168
6


## JadenCase 문자열 만들기
JadenCase : 모든 단어의 첫 문자가 대문자이고 그 외의 알파벳은 소문자인 문자열  
문자열 s를 JadenCase로 바꾼 문자열을 리턴  

제한조건  
s : 길이 1 이상의 문자열, 알파벳과 공백문자

In [23]:
def solution(s):
    answer = ''
    for i in range(len(s)):
        if i == 0 and s[i].isdigit():
            answer += s[i]
        elif i == 0 and s[i].isalpha():
            answer += s[i].upper()
        
        if i != 0 and s[i-1] == ' ':
            answer += s[i].upper()
        elif i != 0:
            answer += s[i].lower()
    return answer

print(solution("3people unFollowed me"))
print(solution("for the last week"))
print(solution("for"))

3people Unfollowed Me
For The Last Week
For


In [24]:
# 다른 사람 -> 지금은 오답
def solution(s):
    return s.title()

print(solution("3people unFollowed me"))
print(solution("for the last week"))
print(solution("for"))

3People Unfollowed Me
For The Last Week
For


## 피보나치 수
2이상의 n이 입력되었을 때 n번째 피보나치 수를 1234567로 나눈 나머지를 리턴  

In [30]:
def solution(n):
    f = [0, 1]
    for i in range(2, n+1):
        f.append(f[i-1] + f[i-2])
    return f[n] % 1234567

print(solution(3))
print(solution(5))
print(solution(100000))

2
5
1168141


## 행렬의 곱셈
2차원 행렬 arr1, arr2 를 입력받아 arr1에 arr2를 곱한 결과를 반환  

In [36]:
def solution(arr1, arr2):
    answer = [[0 for _ in range(len(arr2[0]))] for _ in range(len(arr1))]
    for i in range(len(arr1)):
        for j in range(len(arr2[0])):
            for k in range(len(arr2)):
                answer[i][j] += arr1[i][k] * arr2[k][j]
    return answer

arr1 = [[1, 4], [3, 2], [4, 1]]
arr2 = [[3, 3], [3, 3]]
print(solution(arr1, arr2))

arr1 = [[2, 3, 2], [4, 2, 4], [3, 1, 4]]
arr2 = [[5, 4, 3], [2, 4, 1], [3, 1, 1]]
print(solution(arr1, arr2))

[[15, 15], [15, 15], [15, 15]]
[[22, 22, 11], [36, 28, 18], [29, 20, 14]]


## 최솟값 만들기
길이가 같은 배열 A, B  
A, B 각각 한 개의 숫자를 봅아 두 수를 곱함  
배열의 길이만큼 반복하여 두 수를 곱한 값을 누적 더함.  
최종 누적된 값이 최소가 되도록  
k번째 숫자를 뽑았다면 다음에 k번째 숫자는 뽑을 수 없다.  

제한사항  
A, B 의 길이 : 1,000 이하

In [38]:
def solution(A,B):
    answer = 0
    A.sort()
    B.sort(reverse=True)
    for a, b in zip(A,B):
        answer += a * b
    return answer

A = [1,4,2]
B = [5,4,4]
print(solution(A,B))

A = [1,2]
B = [3,4]
print(solution(A,B))

29
10


## 최댓값과 최솟값
문자열 s, 공백으로 구분된 숫자들  
최소값과 최대값을 찾아 문자열로 반환  

In [45]:
def solution(s):
    answer = ''
    s = list(map(int,s.split()))
    answer += str(min(s)) + ' ' + str(max(s))
    return answer

print(solution("1 2 3 4"))
print(solution("-1 -2 -3 -4"))
print(solution("-1 -1"))

1 4
-4 -1
-1 -1


## 숫자의 표현
자연수 n이 주어질 때 연속된 자연수로 n을 표현하는 방법의 수를 리턴  

In [50]:
def solution(n):
    answer = 0
    tot = 0
    for j in range(1, n+1):
        for i in range(j, n+1):
            tot += i
            if tot == n:
                answer += 1
                tot = 0
                break
            elif tot > n:
                tot = 0
                break
    return answer

print(solution(15))

4


## 올바른 괄호
(로 열렸다면 짝지어서 )로 닫혀야 함  
문자열 s가 올바른 괄호이면 true 반환  
그렇지 않으면 false 반환  

In [51]:
def solution(s):
    stack = []
    for c in s:
        if c == '(':
            stack.append(c)
        else:
            if stack:
                stack.pop()
            else:
                return False
    if not stack:
        return True
    else: 
        return False

print(solution("()()"))
print(solution("(())()"))
print(solution(")()("))
print(solution("(()("))

True
True
False
False


In [52]:
# 다른 사람
def solution(s):
    x = 0
    for w in s:
        if x < 0:
            break
        x = x+1 if w == "(" else x-1 if w == ")" else x
    return x == 0

print(solution("()()"))
print(solution("(())()"))
print(solution(")()("))
print(solution("(()("))

True
True
False
False


## 땅따먹기
땅(land) 는 총 N행 4열로 이루어짐  
모든 칸에는 점수가 쓰여 있다.  
1행부터 땅을 밟으며 한 행씩 내려올 때, 각 행의 4칸 중 한 칸만 밟으며 내려온다.  
같은 열을 연속해서 발을 수 없음  
마지막 행까지 모두 내려왔을 때 얻을 수 있는 점수의 최댓값 리턴  

N : 최대 10^5  

DP??

In [57]:
# 아래 행에 위의 값을 더한다.
# 예전에 비슷한 문제를 본 적이 있다.. 그때도 최댓값 구하기.
def solution(land):
    for r in range(len(land)-1):
        f = max(land[r])
        s = -1
        idx = land[r].index(f)
        for i in range(4):
            if i != idx and land[r][i] > s:
                s = land[r][i]
        for i in range(4):
            if i != idx:
                land[r+1][i] += f
            else:
                land[r+1][i] += s
    return max(land[len(land)-1])

print(solution([[1,2,3,5],[5,6,7,8],[4,3,2,1]]))

16


In [58]:
# 다른 사람
def solution(land):
    for i in range(1, len(land)):
        for j in range(len(land[0])):
            land[i][j] = max(land[i-1][:j] + \
                            land[i-1][j+1:]) + land[i][j]
    return max(land[-1])

print(solution([[1,2,3,5],[5,6,7,8],[4,3,2,1]]))

16


## 가장 큰 정사각형 찾기 (DP)
1과 0으로 채워진 표  
1로 이루어지는 가장 큰 정사각형을 찾아 넓이를 리턴

In [67]:
def solution(board):
    for r in range(len(board)):
        for c in range(len(board[r])):
            if r+1 <= len(board)-1  and c+1 <= len(board[r])-1:
                if board[r][c] != 0 and \
                board[r+1][c] != 0 and\
                board[r][c+1] != 0 and\
                board[r+1][c+1] != 0:
                    board[r+1][c+1] += min(board[r][c], \
                                          board[r+1][c], \
                                          board[r][c+1])
    return max([max(board[i])for i in range(len(board))]) ** 2

print(solution([[0,1,1,1],[1,1,1,1],[1,1,1,1],[0,0,1,0]]))
print(solution([[0,0,1,1],[1,1,1,1]]))

9
4


## 프렌즈 4블록
블록이 2 * 2형태로 4개가 붙어있으면 사라지면서 점수를 얻는다.  
지워지는 조건에 만족하는 2 * 2 모양이 여러개라면 한꺼번에 지워진다.  
블록이 지워진 후 위에 있는 블록이 아래로 떨어져 빈 공간 채운다.  
반복  
지워지는 블록은 모두 몇 개인지 반환하는 함수  


In [85]:
def solution(m, n, board):
    answer = 0
    board = [list(board[i]) for i in range(len(board))]
    while True:
        memo = [[0 for _ in range(n)] for _ in range(m)]
        for r in range(m-1):
            for c in range(n-1):
                t = board[r][c]
                if t != " " and t == board[r+1][c+1] and t == board[r+1][c]\
                and t == board[r][c+1]:
                    memo[r][c] = 1
                    memo[r+1][c] = 1
                    memo[r][c+1] = 1
                    memo[r+1][c+1] = 1
        for ri, line in enumerate(memo):
            for ci, c in enumerate(line):
                if c == 1 and ri > 0:
                    answer += 1
                    i = ri
                    j = ci
                    while i > 0:
                        board[i][j] = board[i-1][j]
                        i -= 1
                        board[i][j] = " "
                elif c == 1 and ri == 0:
                    answer += 1
                    board[ri][ci] = " "
        if sum([sum(memo[i]) for i in range(len(memo))]) == 0:
            break
    return answer

print(solution(4, 5, ["CCBDE", "AAADE", "AAABF", "CCBBF"]))
print(solution(6, 6, ["TTTANT", "RRFACC", "RRRFCC", "TRRRAA", "TTMMMF", "TMMTTJ"]))
print(solution(2,2,["AA", "AA"]))
print(solution(2,2, ["AA", "AB"]))
print(solution(3,2, ["AA", "AA", "AB"]))
print(solution(4,2, ["CC", "AA", "AA", "CC"]))
print(solution(6,2, ["DD", "CC", "AA", "AA", "CC", "DD"]))
print(solution(8,2, ["FF", "AA", "CC", "AA", "AA", "CC", "DD", "FF"]))
print(solution(6,2, ["AA", "AA", "CC", "AA", "AA", "DD"]))


14
15
4
0
4
8
12
8
8


## 튜플

In [110]:
# 각 집합에서 원소마다 등장하는 횟수 세서
# 가장 많이 등장하는 것이 a1
# 가장 적게 등장하는 것이 an ?
def solution(s):
    answer = []
    l = []
    memo = dict()
    for string in s.split("},"):
        l.append(string.replace('}', '').replace('{',''))
    l = [ e.split(',') for e in l ]
    for tup in l:
        for e in tup:
            if not e in memo:
                memo[e] = 1
            else:
                memo[e] += 1
    memo = sorted(memo.items(), key=lambda x: x[1], reverse=True)
    answer = [int(m[0]) for m in memo]
    return answer

print(solution("{{2},{2,1},{2,1,3},{2,1,3,4}}"))
print(solution("{{1,2,3},{2,1},{1,2,4,3},{2}}"))
print(solution("{{20,111},{111}}"))
print(solution("{{123}}"))
print(solution("{{4,2,3},{3},{2,3,4,1},{2,3}}"))


[2, 1, 3, 4]
[2, 1, 3, 4]
[111, 20]
[123]
[3, 2, 4, 1]


In [111]:
# 다른 사람
# 정규식
import re
from collections import Counter

def solution(s):
    s = Counter(re.findall('\d+', s))
    return list(map(int, [k for k, v in sorted(s.items(), \
                                               key=lambda x: x[1], reverse=True)]))

print(solution("{{2},{2,1},{2,1,3},{2,1,3,4}}"))
print(solution("{{1,2,3},{2,1},{1,2,4,3},{2}}"))
print(solution("{{20,111},{111}}"))
print(solution("{{123}}"))
print(solution("{{4,2,3},{3},{2,3,4,1},{2,3}}"))

[2, 1, 3, 4]
[2, 1, 3, 4]
[111, 20]
[123]
[3, 2, 4, 1]


## 스킬트리
가능한 스킬트리의 개수를 리턴  
선행 스킬 순서 skill 배열  
유저가 만든 스킬트리를 담은 배열 skill_trees  

제한조건
스킬은 알파벳 대문자  
스킬이 중복해 주어지지 않는다.  

In [114]:
def solution(skill, skill_trees):
    answer = len(skill_trees)
    i = 0
    for tree in skill_trees:
        i = 0
        for s in tree:
            if s in skill:
                if skill.index(s) == i:
                    i += 1
                else:
                    answer -= 1
                    break
    return answer

skill = "CBD"
skill_trees = ["BACDE", "CBADF", "AECB", "BDA"]
print(solution(skill, skill_trees))

2


In [115]:
# 다른 사람
# for - else 문 ??
def solution(skill, skill_trees):
    answer = 0
    for skills in skill_trees:
        skill_list = list(skill)
        for s in skills:
            if s in skill:
                if s != skill_list.pop(0):
                    break
        else:
            answer += 1
    return answer

skill = "CBD"
skill_trees = ["BACDE", "CBADF", "AECB", "BDA"]
print(solution(skill, skill_trees))

2


## 멀쩡한 사각형
가로 길이 : W  
세로 길이 : H  
직사각형 종이  

누군가 이 종이를 대각선 꼭지점 2개를 잇는 방향으로 잘라 놓음.  
현재 직사각형 종이는 크기가 같은 직각삼각형 2개로 나누어진 상태  

1 * 1로 잘라 사용가능한 정사각형의 개수를 구해라  


In [131]:
from math import gcd
from math import floor
from math import ceil
def solution(w,h):
    g = gcd(w,h)
    dw = w // g
    dh = h // g
    d = h / w
    count = 0
    if h > w:
        for i in range(1, dw + 1):
            y1 = floor(d * (i-1))
            y2 = ceil(d * i)
            count += y2 - y1
            if y2 % dh == 0:
                break
    else:
        for i in range(1, dh + 1):
            x1 = floor((i-1) / d)
            x2 = ceil(i / d)
            count += x2 - x1
            if x2 % dw == 0:
                break
    return w*h - (count * g)
print(solution(8,12))
print(solution(2, 5))
print(solution(2, 3))
print(solution(3, 4))
print(solution(5, 2)) # 4

80
4
2
6
4


In [132]:
# 다른 사람
def gcd(a,b):
    return b if (a==0) else gcd(b%a, a)

def solution(w,h):
    return w*h - w - h + gcd(w,h)

print(solution(8,12))
print(solution(2, 5))
print(solution(2, 3))
print(solution(3, 4))
print(solution(5, 2)) # 4

80
4
2
6
4


## 문자열 압축
문자열에서 같은 값이 연속해서 나타나는 것을 그 문자의 개수와 반복되는 값으로 표현  
aabbaccc -> 2a2ba3c  

문자를 1개 이상의 단위로 잘라서 압축  
ex1) ababcdcdababcdcd  
2 단위 : 2ab2cd2ab2cd  
8 단위 : 2ababcdcd  

ex2) abcabcdede  
2 단위 : abcabc2de  
3 단위 : 2abcdede  

1개 이상의 단위로 문자열을 잘라 압축한 문자열 중 가장 짧은 것의 길이를 리턴  

제한사항  
s의 길이 : 1 ~ 10^3  
s는 알파벳 소문자  
문자열은 제일 앞에서 정해진 길이만큼 잘라야 함  

In [35]:
def solution(s):
    answer = [len(s)]
    chunk = 1
    while chunk <= len(s)//2:
        i = 0
        cnt = 0
        l = len(s)
        while i < len(s):
            if s[i:i+chunk] == s[i+chunk:i+chunk*2]:
                l -= chunk
                cnt += 1
            elif cnt != 0:
                if cnt < 9:
                    l += 1
                elif cnt < 99:
                    l += 2
                elif cnt < 999:
                    l += 3
                elif cnt < 9999:
                    l += 4
                cnt = 0
            i += chunk
#         print(cnt)
#         print(l)
        answer.append(l)
        chunk += 1
    return min(answer)

print(solution("aabbaccc")) # 2a2ba3c -> 7
print(solution("ababcdcdababcdcd"))
print(solution("abcabcdede"))
print(solution("abcabcabcabcdededededede"))
print(solution("xababcdcdababcdcd")) # 17
# 실패 케이스 : 2, 7, 17, 18, 20, 21, 23, 27
# 올림 테스트
print(solution("a"*1000)) # 5 -> 안 되는 것
print(solution('a'*100)) # 4
print(solution('a'*10)) # 3

7
9
8
14
17
5
4
3


In [ ]:
# 다른 사람
def compress(text, tok_len):
    words = [text[i:i+tok_len] for i in range(0, len(text), tok_len)]
    res = []
    cur_word = words[0]
    cur_cnt = 1
    for a, b in zip(words, words[1:] + ['']):
        if a == b:
            cur_cnt += 1
        else:
            res.append([cur_word, cur_cnt])
            cur_word = b
            cur_cnt = 1
    return sum(len(word) + (len(str(cnt)) if cnt > 1 else 0) for word, cnt in res)

def solution(text):
    return min(compress(text, tok_len) for tok_len in list(range(1, int(len(text)/2) + 1)) + [len(text)])

## 조이스틱(탐욕법)
조이스틱으로 알파벳 이름을 완성  

조이스틱의 각 방향  
- 위 : 다음 알파벳
- 아래 : 이전 알파벳
- 왼쪽 커서 이동
- 오른쪽 커서 이동

주어진 이름의 길이만큼 A로 시작한다.  
JAZ 를 만들기 위해  
초기에 AAA 로 시작  

이름에 대해 조이스틱 조작 횟수의 최솟값을 리턴  

In [62]:
def solution(name):
    answer = 0
    init = ["A" for _ in range(len(name))]
    cursor = []
    for i, c in enumerate(name):
        if c != "A" and i != 0: 
            cursor.append(i)
            
    start = 0
    i = 0
    while cursor:
        left = cursor[-1]
        right = cursor[0]
        l = (len(name)-left+start) % len(name)
        r = (right - start) % len(name)
        if l < r:
            answer += l
            cursor.pop()
            start = left
        else:
            answer += r
            cursor.pop(0)
            start = right
        
    for c in name:
        if c == 'A':
            continue
        else:
            val = ord(c) - ord('A')
            move = min(26-val, val)
            answer += move
    return answer

print(solution("JEROEN"))
print(solution("JAZ"))
print(solution("JAN"))
print(solution("AAABAAAA"))
print(solution("ABAAAAAAABA"))
print(solution("AAB"))
print(solution("ZZZ"))
print(solution("AABAAAAAAABBB"))#12
print(solution("BBBBAAAAAB"))#10 -> 답 틀림
print(solution("BBBBAAAABA"))#12 -> 답 틀림
# 아래 두 가지 경우에 대해서 틀리지만
# 프로그래머스에서는 통과됨...
# 다른 사람의 풀이에서도 아래 두 케이스는 통과하지 못 하는 것으로 보임
# 밑에 두 케이스를 풀려면 완전 탐색으로 바꿔야 헐 듯..?

56
11
23
4
6
2
5
12
12
13


## 괄호변환
균형잡힌 : ( 와 )의 개수가 같다  
올바른 : (와 )의 짝이 모두 맞다  

균형잡힌 -> 올바른 변환 과정
1. 입력이 빈 문자열 -> 빈 문자열
2. 문자열 w를 균형잡힌 u, v로 분리 (u: 더 이상 분리흘 수 없는 균형잡힌 문자열, v: 빈 문자열 가능 )
3. u가 올바른 -> v에 대해 1번부터 (수행 결과를 u에 이어 붙여 반환)
4. u가 올바른 X ->
    빈 문자열에 첫 번째 문자로 ( 를 붙임
    v에 대해 1단계부터 재귀적 수행해서 결과를 이어 붙임
    )를 붙임
    u의 첫 번째와 마지막 문자 제거, 나머지 문자열의 괄호 방향을 뒤집어서 뒤에 붙임
    생성된 문자열 반환
    
균형잡힌 p가 주어짐  
올바른 괄호 문자열로 변환한 결과 리턴  

In [64]:
def solution(p):
    answer = ''
    stack = []
    
    # 올바른지 확인
    for c in p:
        if c == '(':
            stack.append(c)
        elif c == ')':
            if stack: stack.pop()
            else: stack.append('(')
                
    if not stack:
        return p
    
    #1
    if p == '':
        return ''
    
    #2
    cnt = 0
    u = ''
    v = ''
    
    u += p[0]
    if p[0] == '(':
        cnt += 1
    else:
        cnt -+ 1
        
    for c in p[1:]:
        if cnt != 0:
            if c == '(':
                u += c
                cnt += 1
            else:
                u += c
                cnt -= 1
            
        if cnt == 0:
            v += c
    v = v[1:]
    
    #3
    stack = []
    for c in u:
        if c == '(':
            stack.append(c)
        elif stack and c == ')':
            stack.pop()
        else:
            stack.append('(')
                
    if not stack:
        answer = u + solution(v)
    else:
        #4
        emp = '('
        emp += solution(v) + ')'
        u = u[1:-1]
        print('e:',emp)
        print('u:',u)
        for c in u:
            if c == '(':
                emp += ')'
            elif c == ')':
                emp += '('
#         emp += u.replace('(', ')').replace(')', '(')
        answer = emp
    
    return answer

# print(solution(""))
# print(solution("(()())()"))
# print(solution(")("))
print(solution("()))((()"))

e: ()
u: ((
e: (())))
u: 
()(())))


## 포켓몬
N 마리의 포켓몬 중 N/2마리를 가져가도 됨  
최대한 많은 종류의 포켓몬을 포함해 N/2마리 선택  
nums : N마리 포켓몬 종류 번호  
가장 많은 종류의 개수 리턴  

제한사항
nums 길이 : 1 ~ 10,000 항상 짝수

In [20]:
from itertools import combinations
from collections import Counter
def solution(nums):
    answer = 0
    comb = list(combinations(nums, len(nums)//2))
    # 시간 초과!!!!
    for tup in comb:
        if answer < len(Counter(tup).keys()):
            answer = len(Counter(tup).keys())
    return answer

print(solution([3,1,2,3]))
print(solution([3,3,3,2,2,4]))
print(solution([3,3,3,2,2,2]))

2
3
2


## 수식 최대화

In [19]:
'''
3가지 연산 문자 : +, -, * -> 우선순위를 모두 다르게 새롭게 정함
우선순위 조합 -> 최대 6개
음수 -> 절댓값으로 변환하여 제출
숫자가 가장 큰 참가자가 우승

expression : 연산 수식 문자열
리턴 : 우승 시 받을 수 있는 가장 큰 상금 금액

같은 연산자 -> 앞에 있는 것이 우선순위 높다
'''
import copy
def solution(expression):
    answer = -1
    op = ["+-*", "+*-", "-+*", "-*+", "*+-", "*-+"]
    
    exp = []
    temp = ""
    for e in expression:
        if e.isnumeric():
            temp += e
        else:
            exp.append(temp)
            temp = ""
            exp.append(e)
    exp.append(temp)
    
    for o in op:
        test = copy.deepcopy(exp)
        for c in o: # o[0] ~ o[2]
            idx = 0
            while len(test) != 1:
                if idx >= len(test):
                    break
                num = test[idx]
                if num == c:
                    if c == '+':
                        val = int(test[idx-1]) + int(test[idx+1])
                    elif c == '-':
                        val = int(test[idx-1]) - int(test[idx+1])
                    elif c == '*':
                        val = int(test[idx-1]) * int(test[idx+1])

                    test.pop(idx-1)
                    test.pop(idx-1)
                    test.pop(idx-1)
                    test.insert(idx-1, val)
                else:
                    idx += 1
            if len(test) == 1 and answer < abs(int(test[0])):
                answer = abs(int(test[0]))
    return answer

# print(solution("100-200*300-500+20"))
print(solution("2000-100"))

['2000', '-', '100']
[1900]
[1900]
['2000', '-', '100']
['2000', '-', '100']
[1900]
[1900]
[1900]
[1900]
[1900]
[1900]
[1900]
['2000', '-', '100']
['2000', '-', '100']
[1900]
['2000', '-', '100']
[1900]
[1900]
1900


## 삼각달팽이

In [47]:
'''
길이와 높이가 n
맨 위 꼭짓점에서 반시계 방향으로 달팽이 채우기
리턴 : 첫 행 ~ 마지막 행 순서대로 합친 배열
'''
import numpy as np
def fill(n, triangle, num, m):
    if len(triangle) == 1:
        triangle[0][0] = num
        return
    
    while triangle[1][1] == 0:
        for r in range(0, n):
            triangle[r][0] = num 
            num += 1
        for c in range(1, n):
            triangle[n-1][c] = num
            num += 1
        for r, c in zip(range(n-2, 0, -1), range(n-2, 0, -1)):
            triangle[r][c] = num
            num += 1
            
    if num == m+1:
        return
    else:
        fill(n-3, triangle[2:n-1, 1:n-2], num, m)

def solution(n):
    answer = []
    # 가장 바깥 삼각형 -> 항상 [1][1] 이 채워지면 끝
    triangle = np.array([[0 for _ in range(n)] for _ in range(n)])
    m = n * (n+1) // 2
    num = 1
    fill(n, triangle, num, m)
    print(triangle)
    for r in triangle.tolist():
        for e in r:
            if e != 0:
                answer.append(e)
    return answer

print(solution(4))
print(solution(6))

[[ 1  0  0  0]
 [ 2  9  0  0]
 [ 3 10  8  0]
 [ 4  5  6  7]]
[1, 2, 9, 3, 10, 8, 4, 5, 6, 7]
[[ 1  0  0  0  0  0]
 [ 2 15  0  0  0  0]
 [ 3 16 14  0  0  0]
 [ 4 17 21 13  0  0]
 [ 5 18 19 20 12  0]
 [ 6  7  8  9 10 11]]
[1, 2, 15, 3, 16, 14, 4, 17, 21, 13, 5, 18, 19, 20, 12, 6, 7, 8, 9, 10, 11]


In [35]:
# 어떻게 2차원 배열의 부분을 주소값으로 전달하지????
# 그냥 배열 말고
# np.array() 로 새로운 변수 할당하고 수정하면 된다 !!!!!!

def test1(matrix, num):
    matrix[0][0] = num
    if num == 10:
        return
    else:
        test1(matrix, num)
    
def test2():
    matrix = [[0 for _ in range(10)] for _ in range(10)]
    for n in range(10):
        test1(matrix, n)
        
m = [[1,2,3,4], [2,3,4,5], [3,4,5,6]]
arr = np.array(m)
print(arr)
print(arr[1:2, 0:2])
arr[1:2, 0:2] = [1, 2]
print(arr)

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]
[[2 3]]
[[1 2 3 4]
 [1 2 4 5]
 [3 4 5 6]]


## 쿼드압축 후 개수 세기

In [48]:
# 다른사람
import numpy as np
def solution(arr):
    def fn(a):
        if np.all(a==0): return np.array([1,0])
        if np.all(a==1): return np.array([0,1])
        n = a.shape[0] // 2
        return fn(a[:n,:n]) + fn(a[n:,:n]) + fn(a[:n,n:]) + fn(a[n:,n:])
    
    return fn(np.array(arr)).tolist()

print(solution([[1,1,0,0],[1,0,0,0],[1,0,0,1],[1,1,1,1]]))

[4, 9]


## 짝지어 제거하기

## 소수 만들기

## 점프와 순간 이동

## 영어 끝말잇기

## 예상 대진표

## 뉴스 클러스터링

## 캐시

## 오픈채팅방

## 후보키

## 방금그곡

## 압축

## 파일명 정렬

## n진수 게임

## 구명보트 (탐욕법)
구명보트 -> 한 번에 최대 2명씩 탈 수 있다 & 무게 제한  
구명보트를 최대한 적게 사용하여 모든 사람을 구출  
people : 사람들의 몸무게를 담은 배열  
limit : 구명보트의 무게 제한  
모든 사람을 구출하기 위해 필요한 구명보트의 최소 개수 리턴  

사람 : 1 ~ 50,000 명  
사람의 무게 : 40 ~ 240  
무게 제한 : 40 ~ 240  
구출할 수 없는 경우 없다  

In [53]:
from collections import deque
def solution(people, limit):
    answer = 0
    q = deque(sorted(people))
    while q:
        n1 = q.popleft()
        if not q:
            answer += 1
        while q:
            n2 = q.pop()
            if n1 + n2 <= limit:
                answer += 1
                break
            else:
                if len(q) == 0:
                    answer += 1
                answer += 1
    return answer

people = [70, 50, 80, 50] # 3
limit = 100
print(solution(people, limit))

people = [20,20,20,20,20,20] # 6
limit = 30
print(solution(people, limit))

people = [70,80,50] # 3
limit = 100
print(solution(people, limit))

people = [10,20,30,40,50,60,70,80,90] # 5
limit = 100
print(solution(people, limit))

people = [20,50,50,80] #2
limit = 100
print(solution(people, limit))

3
6
3
5
2


In [54]:
# 다른 풀이
def solution(people, limit):
    answer = 0
    people.sort()
    
    a = 0
    b = len(people) - 1
    while a < b:
        if people[a] + people[b] <= limit:
            a += 1
            answer += 1
        b -= 1
    return len(people) - answer

people = [70,80,50] # 3
limit = 100
print(solution(people, limit))

people = [10,20,30,40,50,60,70,80,90] # 5
limit = 100
print(solution(people, limit))

people = [20,50,50,80] #2
limit = 100
print(solution(people, limit))

3
5
2


## ** 가장 큰 수  (정렬)

0 또는 양의 정수 -> 정수를 이어 붙여 만들 수 있는 가장 큰 수  
numbers : 0 또는 양의 정수가 담긴 배열  
리턴 : 순서를 재배치해 만들 수 있는 가장 큰 수  

제한  
numbers 길이 : 1 ~ 100,000(10^5) -> 선형 이하  
numbers 원소 : 0 ~ 1,000 -> 1000이라는 최대값을 그냥 준 게 아니다.  
문자열로 리턴  

In [11]:
# 흠 어렵네,, 어떻게 정렬을 구현하지..?
# permutations 사용하면 효율성 때문에 실패함
from itertools import permutations
def solution(numbers):
    numbers = list(map(str, numbers))
    p = list(permutations(numbers))
    l = []
    for tup in p:
        l.append(int(''.join(tup)))
    return str(max(l))

print(solution([6, 10, 2]))
print(solution([3, 30, 34, 5, 9]))
print(solution([22, 43, 91, 97 ,9, 999])) # 9 97 91 43 22
print(solution([40, 403]))

6210
9534330
999997914322
40403


In [19]:
# 구글링..ㅠ
# quick sort를 이용해 우선순위가 높은 값부터 사용
def myQuickSort(nums, l, r):
    if l >= r: return
    pos = partition(nums, l, r)
    myQuickSort(nums, l, pos-1)
    myQuickSort(nums, pos+1, r)
    
def partition(nums, l, r):
    low = l
    while l < r:
        if compare(nums[l], nums[r]):
            nums[l], nums[low] = nums[low], nums[l]
            low += 1
        l += 1
    nums[low], nums[r] = nums[r], nums[low]
    return low

def compare(n1, n2):
    return str(n1) + str(n2) > str(n2) + str(n1)

def solution(numbers):
    myQuickSort(numbers, 0, len(numbers)-1)
    answer = str(int(''.join(map(str, numbers))))
    return answer

print(solution([6, 10, 2]))
print(solution([3, 30, 34, 5, 9]))
print(solution([22, 43, 91, 97 ,9, 999])) # 9 97 91 43 22
print(solution([40, 403]))

6210
9534330
999997914322
40403


In [24]:
# 다른 사람
# numbers 원소가 0 ~ 1000 이라는 조건을 이용
def solution(numbers):
    numbers = list(map(str, numbers))
    numbers.sort(key=lambda x: x*3, reverse=True)
    return str(int(''.join(numbers)))

print(solution([6, 10, 2]))
print(solution([3, 30, 34, 5, 9]))
print(solution([22, 43, 91, 97 ,9, 999])) # 9 97 91 43 22
print(solution([40, 403]))

6210
9534330
999997914322
40403


In [ ]:
# 다른 사람
import functools

def comparator(a, b):
    t1 = a + b
    t2 = b + a
    return (int(t1)>int(t2)) - (int(t1)<int(t2))

def solution(numbers):
    n = [str(x) for x in numbers]
    n = sorted(n, key=functools.cmp_to_key(comparator), reverse=True)
    answer = str(int(''.join(n)))
    return answer

# 새로 알게된 함수 cmp_to_key


In [26]:
'666' < '222' # 문자열끼리 비교

False

In [27]:
'101010' < '666'

True

In [28]:
'101010' < '222'

True